"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.projectDetailRouter = void 0;
/**
 * プロジェクト詳細ルーター
 */
const sdk_1 = require("@cinerino/sdk");
const express = require("express");
const accountingReports_1 = require("../accountingReports");
const accounts_1 = require("../accounts");
const accountStatusTypes_1 = require("../accountStatusTypes");
const accountTitles_1 = require("../accountTitles");
const accountTransactions_1 = require("../accountTransactions");
const actions_1 = require("../actions");
const additionalProperties_1 = require("../additionalProperties");
const applications_1 = require("../applications");
const assetTransactions_1 = require("../assetTransactions");
const authorizations_1 = require("../authorizations");
const categoryCode_1 = require("../categoryCode");
const categoryCodeSets_1 = require("../categoryCodeSets");
const creativeWorks_1 = require("../creativeWorks");
const customers_1 = require("../customers");
const emailMessageAboutIdentifiers_1 = require("../emailMessageAboutIdentifiers");
const emailMessages_1 = require("../emailMessages");
const event_1 = require("../event/event");
const screeningEvent_1 = require("../event/screeningEvent");
const screeningEventSeries_1 = require("../event/screeningEventSeries");
const home_1 = require("../home");
const hub_1 = require("../hub");
const members_1 = require("../iam/members");
const roles_1 = require("../iam/roles");
const merchantReturnPolicies_1 = require("../merchantReturnPolicies");
const offerCatalogs_1 = require("../offerCatalogs");
const offers_1 = require("../offers");
const orders_1 = require("../orders");
const ownershipInfos_1 = require("../ownershipInfos");
const movieTicket_1 = require("../paymentMethods/movieTicket");
const paymentServices_1 = require("../paymentServices");
const people_1 = require("../people");
const permits_1 = require("../permits");
const busStop_1 = require("../places/busStop");
const movieTheater_1 = require("../places/movieTheater");
const screeningRoom_1 = require("../places/screeningRoom");
const screeningRoomSection_1 = require("../places/screeningRoomSection");
const seat_1 = require("../places/seat");
const priceSpecifications_1 = require("../priceSpecifications");
const products_1 = require("../products");
const reservations_1 = require("../reservations");
const sellers_1 = require("../sellers");
const settings_1 = require("../settings");
const tasks_1 = require("../tasks");
const ticketType_1 = require("../ticketType");
const transactions_1 = require("../transactions");
const trips_1 = require("../trips");
const waiter_1 = require("../waiter");
const projectDetailRouter = express.Router();
exports.projectDetailRouter = projectDetailRouter;
projectDetailRouter.use('/home', home_1.homeRouter);
projectDetailRouter.use('/accountingReports', accountingReports_1.accountingReportsRouter);
projectDetailRouter.use('/accounts', accounts_1.accountsRouter);
projectDetailRouter.use('/accountStatusTypes', accountStatusTypes_1.accountStatusTypesRouter);
projectDetailRouter.use('/accountTitles', accountTitles_1.accountTitlesRouter);
projectDetailRouter.use('/accountTransactions', accountTransactions_1.accountTransactionsRouter);
projectDetailRouter.use('/actions', actions_1.actionsRouter);
projectDetailRouter.use('/additionalProperties', additionalProperties_1.additionalPropertiesRouter);
projectDetailRouter.use('/applications', applications_1.applicationsRouter);
projectDetailRouter.use('/assetTransactions', assetTransactions_1.assetTransactionsRouter);
projectDetailRouter.use('/authorizations', authorizations_1.authorizationsRouter);
projectDetailRouter.use('/categoryCodes', categoryCode_1.categoryCodesRouter);
projectDetailRouter.use('/categoryCodeSets', categoryCodeSets_1.categoryCodeSetsRouter);
projectDetailRouter.use('/creativeWorks', creativeWorks_1.creativeWorksRouter);
projectDetailRouter.use('/customers', customers_1.customersRouter);
projectDetailRouter.use('/emailMessageAboutIdentifiers', emailMessageAboutIdentifiers_1.emailMessageAboutIdentifiersRouter);
projectDetailRouter.use('/emailMessages', emailMessages_1.emailMessagesRouter);
projectDetailRouter.use(`/events/${sdk_1.factory.eventType.Event}`, event_1.eventRouter);
projectDetailRouter.use('/events/screeningEvent', screeningEvent_1.screeningEventRouter);
projectDetailRouter.use('/events/screeningEventSeries', screeningEventSeries_1.screeningEventSeriesRouter);
projectDetailRouter.use('/hub', hub_1.hubRouter);
projectDetailRouter.use('/iam/members', members_1.iamMembersRouter);
projectDetailRouter.use('/iam/roles', roles_1.iamRolesRouter);
projectDetailRouter.use('/merchantReturnPolicies', merchantReturnPolicies_1.merchantReturnPoliciesRouter);
projectDetailRouter.use('/offerCatalogs', offerCatalogs_1.offerCatalogsRouter);
projectDetailRouter.use('/offers', offers_1.offersRouter);
projectDetailRouter.use('/orders', orders_1.ordersRouter);
projectDetailRouter.use('/ownershipInfos', ownershipInfos_1.ownershipInfosRouter);
projectDetailRouter.use('/paymentMethods/movieTicket', movieTicket_1.movieTicketPaymentMethodRouter);
projectDetailRouter.use('/paymentServices', paymentServices_1.paymentServicesRouter);
projectDetailRouter.use('/people', people_1.peopleRouter);
projectDetailRouter.use('/places/busStop', busStop_1.busStopRouter);
projectDetailRouter.use('/places/movieTheater', movieTheater_1.movieTheaterRouter);
projectDetailRouter.use('/places/screeningRoom', screeningRoom_1.screeningRoomRouter);
projectDetailRouter.use('/places/screeningRoomSection', screeningRoomSection_1.screeningRoomSectionRouter);
projectDetailRouter.use('/places/seat', seat_1.seatRouter);
projectDetailRouter.use('/priceSpecifications', priceSpecifications_1.priceSpecificationsRouter);
projectDetailRouter.use('/products', products_1.productsRouter);
projectDetailRouter.use('/reservations', reservations_1.reservationsRouter);
projectDetailRouter.use('/sellers', sellers_1.sellersRouter);
projectDetailRouter.use('/serviceOutputs', permits_1.permitsRouter);
projectDetailRouter.use('/settings', settings_1.settingsRouter);
projectDetailRouter.use('/tasks', tasks_1.tasksRouter);
projectDetailRouter.use('/ticketTypes', ticketType_1.ticketTypeMasterRouter);
projectDetailRouter.use('/transactions', transactions_1.transactionsRouter);
projectDetailRouter.use('/trips', trips_1.tripsRouter);
projectDetailRouter.use('/waiter', waiter_1.waiterRouter);
